In [1]:
from bokeh.plotting import figure, output_file, show
import pandas as pd

In [26]:
tempdf = pd.read_csv('working1.csv', parse_dates = ['Year'])
p = figure(width = 800, height = 250, x_axis_type = 'datetime')
p.line(tempdf['Year'], tempdf['SO2'], color = 'blue', alpha = 0.5)
output_file('polution_data.html')
show(p)

In [11]:
tempdf = df.groupby(['Year']).sum().reset_index()

In [12]:
tempdf.head()

,Year,Air Temperature,Pressure Station Level,Pressure Mean Sea Level,Relative Humidity,Horizontal Visibility,Dew Point Temperature,PM2.5,PM10,NO2,...,D-1 NO2,D-1 SO2,Date_n,Wind Speed,D-2 PM10,D-3 PM10,D-4 PM10,D-5 PM10,D-6 PM10,D-7 PM10
0,2013,9578.126841,275428.608547,275547.139264,27223.691435,1044.077096,7586.766700,12995.50,39463.33,18762.28,...,18801.06,3379.56,432344,896.960168,39443.42,39398.79,39372.71,39340.20,39252.07,39286.12
1,2014,9684.925561,275655.877041,275774.809521,26924.214916,985.400348,7613.040327,13818.00,44121.04,18579.76,...,18497.97,3278.50,432709,898.707182,43815.10,43855.07,43902.74,43912.91,43911.58,43800.50
2,2015,9829.790252,275813.621341,275931.356237,27381.163325,990.616016,7888.525151,12264.50,41850.67,19798.79,...,19839.21,2553.64,433074,894.243623,41584.65,41638.53,41622.63,41626.72,41695.62,41745.96
3,2016,10019.988400,276325.818129,276442.786350,27480.744371,1016.229971,8063.113974,24344.25,45262.39,15619.41,...,15647.79,1751.68,435630,945.459734,45406.09,45378.23,45328.47,45252.92,45097.70,44955.99
4,2017,9703.632599,275584.750694,275702.871390,27362.551704,1068.437345,7761.068115,25084.50,44226.24,14525.65,...,14538.86,2422.19,433804,1053.979249,44223.82,44215.11,44280.50,44353.24,44461.27,44535.97

In [8]:
df = pd.read_csv('merged_new.csv')

In [10]:
df['Year']

0       2013
1       2013
2       2013
3       2013
4       2013
        ...
2367    2019
2368    2019
2369    2019
2370    2019
2371    2019
Name: Year, Length: 2372, dtype: int64

In [19]:
tempdf.to_csv('working1.csv')